"""empty message

Revision ID: 75d56e8a6e12
Revises: 0d1b02cfe3d5
Create Date: 2022-11-07 10:55:53.433901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75d56e8a6e12'
down_revision = '0d1b02cfe3d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('recruiter_id', table_name='company')
    op.drop_constraint('company_ibfk_1', 'company', type_='foreignkey')
    op.drop_column('company', 'recruiter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('recruiter_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('company_ibfk_1', 'company', 'recruiter', ['recruiter_id'], ['id'])
    op.create_index('recruiter_id', 'company', ['recruiter_id'], unique=False)
    # ### end Alembic commands ###
