"""added recruiter id to job

Revision ID: e1c826ea002d
Revises: e411a7c3a191
Create Date: 2022-11-02 10:11:42.999739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1c826ea002d'
down_revision = 'e411a7c3a191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('recruiter_id', table_name='company')
    op.drop_constraint('company_ibfk_1', 'company', type_='foreignkey')
    op.drop_column('company', 'recruiter_id')
    op.add_column('job', sa.Column('recruiter_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'job', ['recruiter_id'])
    op.create_foreign_key(None, 'job', 'recruiter', ['recruiter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_constraint(None, 'job', type_='unique')
    op.drop_column('job', 'recruiter_id')
    op.add_column('company', sa.Column('recruiter_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('company_ibfk_1', 'company', 'recruiter', ['recruiter_id'], ['id'])
    op.create_index('recruiter_id', 'company', ['recruiter_id'], unique=False)
    # ### end Alembic commands ###
