"""cleaned up models

Revision ID: e411a7c3a191
Revises: 6170d6187036
Create Date: 2022-11-01 18:16:04.793818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e411a7c3a191'
down_revision = '6170d6187036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='job')
    op.add_column('recruiter', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('recruiter', sa.Column('inactive_date', sa.DateTime(), nullable=True))
    op.drop_index('first_name', table_name='recruiter')
    op.drop_index('last_name', table_name='recruiter')
    op.drop_column('recruiter', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recruiter', sa.Column('status', mysql.VARCHAR(length=80), nullable=True))
    op.create_index('last_name', 'recruiter', ['last_name'], unique=False)
    op.create_index('first_name', 'recruiter', ['first_name'], unique=False)
    op.drop_column('recruiter', 'inactive_date')
    op.drop_column('recruiter', 'active')
    op.create_index('name', 'job', ['name'], unique=False)
    # ### end Alembic commands ###
