"""empty message

Revision ID: 0d1b02cfe3d5
Revises: e1c826ea002d
Create Date: 2022-11-07 10:52:56.387351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1b02cfe3d5'
down_revision = 'e1c826ea002d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('recruiter_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'company', ['recruiter_id'])
    op.create_foreign_key(None, 'company', 'recruiter', ['recruiter_id'], ['id'])
    op.add_column('job', sa.Column('recruiter_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'job', ['recruiter_id'])
    op.create_foreign_key(None, 'job', 'recruiter', ['recruiter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_constraint(None, 'job', type_='unique')
    op.drop_column('job', 'recruiter_id')
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_column('company', 'recruiter_id')
    # ### end Alembic commands ###
