"""remove company phone

Revision ID: f48efe2a4a30
Revises: 0a47079d35d9
Create Date: 2022-11-08 19:16:55.786309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f48efe2a4a30'
down_revision = '0a47079d35d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='company')
    op.drop_column('company', 'phone')
    op.create_foreign_key(None, 'job', 'company', ['company_id'], ['id'])
    op.create_foreign_key(None, 'job', 'recruiter', ['recruiter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.add_column('company', sa.Column('phone', mysql.VARCHAR(length=20), nullable=False))
    op.create_index('phone', 'company', ['phone'], unique=False)
    # ### end Alembic commands ###
